app.debug=true
drools.langLevel=1.6
notification.host=localhost:18070
notification_ws.host=localhost:18061
notification_ws.enabled=true
modules.ext.dir=/modules

cloud_channel=${channelgroup}

filipizen_server_ip=192.168.2.15
filipizen_server_host=192.168.2.15:90
filipizen_server_scheme=http
